import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Standard Interview Aufgabenstellung',
  description: 'Generated by create next app',
};
type Props = {
  children: ReactNode;
};

export default function RootLayout(props: Props) {
  return (
    <html lang="de">
      <body className={inter.className}>
        {props.children}
        <footer>
          <nav>menu bar</nav>
        </footer>
      </body>
    </html>
  );
}
